table Dim_Fecha
	lineageTag: 9575298f-d7f2-42e1-9d40-606c97590cd6

	column Fecha
		dataType: dateTime
		formatString: General Date
		lineageTag: ad7a9a8e-b01e-44a2-aaae-37b13f2d58e3
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: bbf80337-4dab-4b29-b2b5-291bb176b30f
			defaultHierarchy: LocalDateTable_72b6925e-8dce-4be6-9452-a7012b2d6073.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 1cf8de18-edb4-463d-bdcc-a493455a5ffa
		summarizeBy: count
		sourceColumn: Año

		annotation SummarizationSetBy = User

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: 178d720c-b5f0-45d3-ae3b-ca7342a63729
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Nombre_Mes
		dataType: string
		lineageTag: fc1cc6ba-7af3-4a6f-91a6-57e4fd016e07
		summarizeBy: none
		sourceColumn: Nombre_Mes

		annotation SummarizationSetBy = Automatic

	column Día
		dataType: int64
		formatString: 0
		lineageTag: 35f25a43-b4cc-422e-ba7d-c95e3ddbf627
		summarizeBy: sum
		sourceColumn: Día

		annotation SummarizationSetBy = Automatic

	column Día_Semana
		dataType: string
		lineageTag: 1846d4a7-119f-4e64-a09e-359915fe37b2
		summarizeBy: none
		sourceColumn: Día_Semana

		annotation SummarizationSetBy = Automatic

	partition Dim_Fecha = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Camilo\Desktop\BD_Auditoria_ETL_Periodo2_Profesional (1).xlsx"), null, true),
				    Dim_Fecha_Sheet = Origen{[Item="Dim_Fecha",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Dim_Fecha_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Fecha", type datetime}, {"Año", Int64.Type}, {"Mes", Int64.Type}, {"Nombre_Mes", type text}, {"Día", Int64.Type}, {"Día_Semana", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

