table 'Tabla 1 (Auditores)'
	lineageTag: fd3c63c8-f7f7-4bc3-9d39-97d2894210cb

	column Auditor_ID
		dataType: int64
		formatString: 0
		lineageTag: 018b216a-fc49-4ee4-b20c-e03884f041d3
		summarizeBy: count
		sourceColumn: Auditor_ID

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: e3bf786b-45c7-4ca3-a977-9aad5b1038e5
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Especialidad
		dataType: string
		lineageTag: 99a9dec7-1542-4dc9-8e2c-3ed1d1b90a0c
		summarizeBy: count
		sourceColumn: Especialidad

		annotation SummarizationSetBy = User

	partition 'Tabla 1 (Auditores)' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Daniel Hrndz\Desktop\BD_Auditoria_ETL_Periodo2_Profesional.xlsx"), null, false),
				    Auditores_sheet = Origen{[Item="Auditores",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Otras columnas quitadas" = Table.SelectColumns(Auditores_sheet, List.Select(Table.ColumnNames(Auditores_sheet), each try not List.IsEmpty(FilterNullAndWhitespace(Table.Column(Auditores_sheet, _))) otherwise true)),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Otras columnas quitadas", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Auditor_ID", Int64.Type}, {"Nombre", type text}, {"Especialidad", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

